name: Ping backend en Render

on:
  schedule:
    # - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC (~9 AM ARG)
    - cron: '5 15 * * *'  # Todos los días a las 15:05 UTC (~12:05 PM ARG)

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer ping a backend Render
        run: curl -s -o /dev/null -w "%{http_code}" https://rejas-espaciales-backend-v2.onrender.com/api/ping
